from __future__ import annotations

from app.controllers.overlay_commands import OverlayCommand


ACTION_SPECS = {'back': {'kind': 'menu_nav', 'command': 'back'},
 'close': {'kind': 'menu_nav', 'command': 'exit'},
 'turn_screen_off': {'kind': 'custom', 'name': 'turn_screen_off'},
 'cover_kitchen': {'kind': 'mqtt_action', 'action': 'cover_kitchen_toggle'},
 'cinema': {'kind': 'mqtt_action', 'action': 'cinema_toggle'},
 'bed_heating': {'kind': 'mqtt_action', 'action': 'bed_heating_toggle'},
 'beamer_on': {'kind': 'mqtt_action', 'action': 'beamer_on'},
 'beamer_off': {'kind': 'mqtt_action', 'action': 'beamer_off'},
 'soundbar_toggle': {'kind': 'mqtt_action', 'action': 'soundbar_toggle'},
 'soundbar_mute': {'kind': 'mqtt_action', 'action': 'soundbar_mute'},
 'soundbar_hdmi': {'kind': 'mqtt_action', 'action': 'soundbar_hdmi'},
 'soundbar_volume_down': {'kind': 'mqtt_action', 'action': 'soundbar_volume_down'},
 'soundbar_volume_up': {'kind': 'mqtt_action', 'action': 'soundbar_volume_up'},
 'ps_toggle': {'kind': 'mqtt_action', 'action': 'ps_toggle'},
 'scene_dinner': {'kind': 'mqtt_action', 'action': 'scene_dinner'},
 'scene_bright': {'kind': 'mqtt_action', 'action': 'scene_bright'},
 'scene_movie': {'kind': 'mqtt_action', 'action': 'scene_movie'},
 'scene_romantic': {'kind': 'mqtt_action', 'action': 'scene_romantic'},
 'scene_off': {'kind': 'mqtt_action', 'action': 'scene_off'},
 'blinds_down': {'kind': 'mqtt_action', 'action': 'blinds_down'},
 'blinds_up': {'kind': 'mqtt_action', 'action': 'blinds_up'},
 'blinds_stop': {'kind': 'mqtt_action', 'action': 'blinds_stop'},
 'light_woonkamer': {'kind': 'mqtt_action', 'action': 'light_woonkamer_toggle'},
 'light_keuken': {'kind': 'mqtt_action', 'action': 'light_keuken_toggle'},
 'light_kleur': {'kind': 'mqtt_action', 'action': 'light_kleur_toggle'},
 'light_tafel': {'kind': 'mqtt_action', 'action': 'light_tafel_toggle'},
 'in_bed_toggle': {'kind': 'mqtt_action', 'action': 'in_bed_toggle'},
 'doorbell': {'kind': 'custom', 'name': 'doorbell'},
 'calendar': {'kind': 'mqtt_action', 'action': 'calendar'},
 'calendar_add': {'kind': 'show_image', 'image': 'qr-agenda.png'},
 'wifi_qr': {'kind': 'show_image', 'image': 'qr-wifi.png'},
 'trash_warning_toggle': {'kind': 'mqtt_action', 'action': 'trash_warning_toggle'},
 'music_play_pause': {'kind': 'media', 'op': 'play_pause'},
 'music_volume_up': {'kind': 'media', 'op': 'volume', 'arg': 'up'},
 'music_volume_down': {'kind': 'media', 'op': 'volume', 'arg': 'down'},
 'music_next': {'kind': 'media', 'op': 'skip', 'arg': 'next'},
 'music_previous': {'kind': 'media', 'op': 'skip', 'arg': 'previous'},
 'music_show_title': {'kind': 'custom', 'name': 'music_show_title'},
 'heart': {'kind': 'overlay', 'command': 'open_slideshow'},
 'christmas': {'kind': 'mqtt_action', 'action': 'activate_christmas'},
 '3d_printer_status': {'kind': 'overlay', 'command': 'show_print_status'},
 '3d_printer_cam': {'kind': 'overlay', 'command': 'show_cam'},
 'show_weather_on_idle': {'kind': 'setting_toggle', 'attr': 'show_weather_on_idle'},
 'verify_ssl_on_trusted_sources': {'kind': 'setting_toggle', 'attr': 'verify_ssl_on_trusted_sources'},
 'media_show_titles': {'kind': 'setting_toggle', 'attr': 'media_show_titles'},
 'media_sanitize_titles': {'kind': 'setting_toggle', 'attr': 'media_sanitize_titles'},
 'force_update': {'kind': 'setting_toggle', 'attr': 'force_update'},
 'enable_network_simulation': {'kind': 'setting_toggle', 'attr': 'enable_network_simulation'},
 'store_settings': {'kind': 'setting_toggle', 'attr': 'store_settings'},
 'shell_reboot': {'kind': 'shell', 'op': 'reboot'},
 'shell_shutdown': {'kind': 'shell', 'op': 'shutdown'},
 'exit': {'kind': 'app_exit'},
 'test_mij': {'kind': 'custom', 'name': 'test_mij_todo'},
 'test_mij_todo': {'kind': 'custom', 'name': 'test_mij_todo'}}
